AWSTemplateFormatVersion: '2010-09-09'

# AWS CF cannot deploy S3 and Lambda. S3 Bucket needs to be deployed first

Parameters:
  LambdaFunctionName:
    Type: String
    Description: Name for the Lambda function
    Default: poc-aws-lambda-js
    AllowedPattern: "([A-Za-z0-9_+=,.@-]){0,50}" # max 64 characters for role

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${LambdaFunctionName}-bucket'
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
