name: Development
on:
  push:
    branches: [ master ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: development
    steps:

    # Checkout code
    - name: Checkout
      uses: actions/checkout@v3

    # Login to AWS
    - name: Login to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
        aws-region: eu-west-2

    # Upload code to S3 bucket
    - name: Upload Application Code
      run: |
        cd ./src
        mkdir output
        zip ./output/app.zip index.js index.html
        aws s3 sync ./output/ s3://${{ vars.S3_BUCKET_NAME }}

    # Deploy Infrastructure
    - name: Deploy Infrastructure
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: "${{ vars.PROJECT_NAME }}" # Name of the cloud formation stack (updates existing one)
        template: ./infrastructure/main.yaml
        capabilities: "CAPABILITY_IAM,CAPABILITY_NAMED_IAM"
        parameter-overrides: >-
          ProjectName=${{ vars.PROJECT_NAME }},
          Runtime=${{ vars.RUNTIME }},
          Environment=Development,
          LambdaFunctionName=${{ vars.LAMBDA_FUNCTION_NAME }},
          DynamoDBTableName=${{ vars.DYNAMO_DB_TABLE_NAME }},
          S3BucketName=${{ vars.S3_BUCKET_NAME }}
        no-fail-on-empty-changeset: "1" # Do not fail the deployment if nothing changed
